
export const T = {
  bgPage:    "#E8F5F0",
  bgSidebar: "#1B3A35",
  bgCard:    "#FFFFFF",
  teal:      "#2A7A6A",
  tealLight: "#D4EDE8",
  tealMid:   "#5BA89A",
  textDark:  "#1A2E2A",
  textMid:   "#4A6560",
  textLight: "#8AABA5",
  border:    "#D0E8E2",
  danger:    "#E05555",
  dangerBg:  "#FDEAEA",
  success:   "#2A9D6F",
  successBg: "#E6F7F0",
};

export const G = {
  page:      { display:"flex", minHeight:"100vh", background:T.bgPage, fontFamily:"'DM Sans','Segoe UI',sans-serif", color:T.textDark },
  sidebar:   { width:220, background:T.bgSidebar, display:"flex", flexDirection:"column", padding:"24px 0", flexShrink:0, position:"sticky", top:0, height:"100vh" },
  sidebarLogo:     { padding:"0 20px 28px", borderBottom:"1px solid rgba(255,255,255,0.08)" },
  sidebarLogoText: { fontSize:16, fontWeight:700, color:"#fff", letterSpacing:"0.02em" },
  sidebarSub:      { fontSize:11, color:T.tealMid, marginTop:2 },
  sidebarNav:      { flex:1, padding:"12px 0" },
  navItem: (a) => ({ display:"flex", alignItems:"center", gap:10, padding:"10px 20px", cursor:"pointer", background: a ? "rgba(90,168,154,0.18)" : "transparent", borderLeft: a ? `3px solid ${T.tealMid}` : "3px solid transparent", color: a ? "#fff" : "rgba(255,255,255,0.55)", fontSize:13, fontWeight: a ? 600 : 400, transition:"all 0.15s" }),
  main:      { flex:1, padding:"28px 32px", minWidth:0 },
  pageHeader:{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:24 },
  pageTitle: { fontSize:22, fontWeight:700, color:T.textDark },
  pageSubtitle:{ fontSize:13, color:T.textMid, marginTop:2 },
  card:      { background:T.bgCard, borderRadius:12, border:`1px solid ${T.border}`, overflow:"hidden" },
  table:     { width:"100%", borderCollapse:"collapse", fontSize:13 },
  th:        { padding:"10px 14px", textAlign:"left", background:"#F4FAF8", color:T.textMid, fontWeight:600, fontSize:12, textTransform:"uppercase", letterSpacing:"0.04em", borderBottom:`1px solid ${T.border}` },
  td:        { padding:"12px 14px", borderBottom:`1px solid ${T.border}`, color:T.textDark, verticalAlign:"middle" },
  btnPrimary:   { background:T.teal, color:"#fff", border:"none", borderRadius:8, padding:"9px 18px", fontSize:13, fontWeight:600, cursor:"pointer", display:"flex", alignItems:"center", gap:6 },
  btnSecondary: { background:"transparent", color:T.teal, border:`1px solid ${T.teal}`, borderRadius:8, padding:"8px 16px", fontSize:13, fontWeight:600, cursor:"pointer" },
  btnDanger:    { background:"transparent", color:T.danger, border:`1px solid ${T.danger}`, borderRadius:6, padding:"5px 12px", fontSize:12, fontWeight:600, cursor:"pointer" },
  input:     { width:"100%", padding:"9px 12px", border:`1px solid ${T.border}`, borderRadius:8, fontSize:13, color:T.textDark, background:"#fff", outline:"none", boxSizing:"border-box" },
  select:    { width:"100%", padding:"9px 12px", border:`1px solid ${T.border}`, borderRadius:8, fontSize:13, color:T.textDark, background:"#fff", outline:"none", boxSizing:"border-box" },
  label:     { fontSize:12, fontWeight:600, color:T.textMid, marginBottom:5, display:"block" },
  formGroup: { display:"flex", flexDirection:"column", marginBottom:14 },
  modal:     { position:"fixed", inset:0, zIndex:100, display:"flex", alignItems:"center", justifyContent:"center" },
  modalOverlay: { position:"absolute", inset:0, background:"rgba(20,45,40,0.45)" },
  modalBox:  { position:"relative", background:"#fff", borderRadius:14, padding:"28px 32px", width:"100%", maxWidth:500, boxShadow:"0 20px 60px rgba(0,0,0,0.18)", zIndex:1 },
  badge: (color, bg) => ({ display:"inline-block", padding:"3px 10px", borderRadius:20, fontSize:11, fontWeight:700, color, background:bg }),
  statCard:  { background:T.bgCard, borderRadius:12, border:`1px solid ${T.border}`, padding:"18px 22px" },
  statNum:   { fontSize:28, fontWeight:700, color:T.teal },
  statLabel: { fontSize:12, color:T.textMid, marginTop:4, fontWeight:500 },
  searchBar: { display:"flex", gap:10, alignItems:"center", padding:"14px 20px", borderBottom:`1px solid ${T.border}` },
  searchInput:{ flex:1, padding:"8px 12px", border:`1px solid ${T.border}`, borderRadius:8, fontSize:13, outline:"none", background:T.bgPage },
  alert: (t) => ({ padding:"10px 14px", borderRadius:8, fontSize:13, marginBottom:14, background: t==="success" ? T.successBg : T.dangerBg, color: t==="success" ? T.success : T.danger, border:`1px solid ${t==="success" ? "#A8DFC8" : "#F5BEBE"}` }),
  empty:     { textAlign:"center", padding:"40px 20px", color:T.textLight, fontSize:13 },
  loading:   { textAlign:"center", padding:"40px 20px", color:T.textMid, fontSize:13 },
};
